### ISSUE TITLE
Could you provide the code of Patch Attack Evaluation?

### ISSUE THREAD

**Issue by 1104662797** [ytongbai/ViTs-vs-CNNs#3]
Thanks very much

**Comment by ytongbai** [comment]
Hi, thanks for your interests! Please exactly follow https://github.com/Chenglin-Yang/PatchAttack, it provides the attacking dictionary and code, with detailed explanation.

**Comment by 1104662797** [comment]
Thanks for your reply, I have read the code, but there are so many parameter to set by myself, like `area_occlu`,  `TPA_n_agents` and `target`, I am so confusion about that.

**Comment by ytongbai** [comment]
I see. According to our paper(Section 4.2),  by default, we set the number of attacking patches to 4, limit the largest
manipulated area to 10% of the whole image area, and set the attack mode as the non-targeted attack.

**Comment by 1104662797** [comment]
I am so sorry for this stupid question, I have finished the code, but the generated picture have same patch in the same place. the code I use is this :`configure_PA(
        t_name='/home/host/mounted2/imagenet-/TextureDict/TextureDict_ImageNet',
        t_labels = np.arange(1000).tolist(),
        area_occlu = 0.1,
        n_occlu = 1,
        rl_batch=500, steps=50,
        TPA_n_agents=4,
    )
    TPA = PA.TPA(dir_title)

    ## tpa attack and eval
    criterion = torch.nn.CrossEntropyLoss()
    metric_logger = utils.MetricLogger(delimiter="  ")
    header = 'Test:'
    for images, target in metric_logger.log_every(data_loader, 1000, header):
        input_tensor = images.to(device, non_blocking=True)
        label_tensor = target.to(device, non_blocking=True)
        adv_img, rcd_list = TPA.attack(
            model = model,
            target = 723,
            input_tensor = input_tensor[0,:,:,:],
            label_tensor = label_tensor,
        )
`  Thanks for your help

**Comment by ytongbai** [comment]
Hi, I believe this question is only regarding PatchAttack, please turn to  https://github.com/Chenglin-Yang/PatchAttack for more discussion and help.
