### ISSUE TITLE
About the output of autoattack. And the program will be killed by themself.

### ISSUE THREAD

**Issue by 1104662797** [ytongbai/ViTs-vs-CNNs#4]
When I use your code of autoatteck, the output I get is very different, and the program will be killed by them self.  After output the APGD-CE accuracy, the terminal output **Killed**.
the part output of mine :
```
apgd-ce - 1/147 - 256 out of 256 successfully perturbed
0.74022
apgd-ce - 2/147 - 256 out of 256 successfully perturbed
0.7351
apgd-ce - 3/147 - 256 out of 256 successfully perturbed
0.72998
apgd-ce - 4/147 - 256 out of 256 successfully perturbed
0.72486
apgd-ce - 5/147 - 256 out of 256 successfully perturbed
0.71974
apgd-ce - 6/147 - 256 out of 256 successfully perturbed
0.71462
apgd-ce - 7/147 - 256 out of 256 successfully perturbed
0.7095
apgd-ce - 8/147 - 256 out of 256 successfully perturbed
0.70438
apgd-ce - 9/147 - 256 out of 256 successfully perturbed
0.69926
apgd-ce - 10/147 - 256 out of 256 successfully perturbed
0.69414
apgd-ce - 11/147 - 256 out of 256 successfully perturbed
0.68902
apgd-ce - 12/147 - 256 out of 256 successfully perturbed
0.6839
apgd-ce - 13/147 - 256 out of 256 successfully perturbed
0.67878
apgd-ce - 14/147 - 256 out of 256 successfully perturbed
0.67366
apgd-ce - 15/147 - 256 out of 256 successfully perturbed
```
the follow is the part output of yours(autoattack/log)
```
apgd-ce - 1/65 - 193 out of 512 successfully perturbed
0.65892
apgd-ce - 2/65 - 116 out of 512 successfully perturbed
0.65402
apgd-ce - 3/65 - 245 out of 512 successfully perturbed
0.64836
apgd-ce - 4/65 - 283 out of 512 successfully perturbed
0.64416
apgd-ce - 5/65 - 210 out of 512 successfully perturbed
0.6403
apgd-ce - 6/65 - 193 out of 512 successfully perturbed
0.63828
apgd-ce - 7/65 - 101 out of 512 successfully perturbed
0.6342
apgd-ce - 8/65 - 204 out of 512 successfully perturbed
0.62892
apgd-ce - 9/65 - 264 out of 512 successfully perturbed
0.62626
```
Thanks for your reply

**Comment by ytongbai** [comment]
Hi, from the log, it looks like we used different batch size. For example, for last step of our log: 'apgd-ce - 9/65 - 264 out of 512 successfully perturbed', our attack processed to 9/65, which roughly equals to 20/147 of yours. So I think this different pace causes the different output.

As for the killed program, I would suggest monitor the CPU status. This autoattack package do require stronger CPU computation. If your CPU is overloaded, it would be killed by your machine.

**Comment by 1104662797** [comment]
Thanks for your help. I mean this different :283 out of 512 successfully perturbed(I get 256 out of 256 successfully perturbed) is this norm?

**Comment by ytongbai** [comment]
Yeah I wouldn't worry too much of it. It's also caused by different batch sizes and it is the per-iter log. You can just look at the final number :)
