### ISSUE TITLE
Is epsilon 4/255 or 8/255 in adversarial training?

### ISSUE THREAD

**Issue by ShihuaHuang95** [ytongbai/ViTs-vs-CNNs#7]
Hi, Thanks for this excellent work! 
You stated in your paper "with the constrain that maximum per-pixel change epsilon = 4/255". 
However, in this implementation, the argument **_attack-epsilon_** (4) is multiplied by an [Image Scale which is 2/255](https://github.com/ytongbai/ViTs-vs-CNNs/blob/main/models/attacker.py#L6), and the real epsilon should be 8/255 instead of 4/255?

**Comment by mo666666** [comment]
Hello, guys, do you try to adversarially train DeiT? The top-1 accuracy on the evaluation set is quite low. I am not sure whether it is my problem or the bugs in the code.

**Comment by mo666666** [comment]
I also have a question for the accuracy in the original paper. Is that top-1 accuracy or top-5 accuracy?

**Comment by cihangxie** [comment]
The effective epsilon is 4/255. The reason that we use the image scale 2/255 in adversarial training is that we apply [IMAGENET_INCEPTION_MEAN, IMAGENET_INCEPTION_STD], as suggested here,

1) https://github.com/ytongbai/ViTs-vs-CNNs/blob/09687f4570cbdfcc0cf1aab71a4417a5c32feda8/main_adv_deit.py#L61
2) https://github.com/ytongbai/ViTs-vs-CNNs/blob/09687f4570cbdfcc0cf1aab71a4417a5c32feda8/datasets.py#L84

to normalize images. This normalization will convert the image scale from [0, 1] to [-1, 1].

**Comment by ksouvik52** [comment]
@ShihuaHuang95 Were you able to train it successfully train advdeit.sh? The accuracy seems pretty low for me

**Comment by ksouvik52** [comment]
{"train_lr": 1.0000000000000031e-06, "train_loss": 6.885785259502969, "test_0_loss": 6.7725973782139715, "test_0_acc1": 0.806, "test_0_acc5": 2.804, "test_5_loss": 6.844994894602477, "test_5_acc1": 0.55, "test_5_acc5": 1.958, "epoch": 0, "n_parameters": 22050664}
{"train_lr": 1.0000000000000031e-06, "train_loss": 6.885785259502969, "test_0_loss": 6.7725973782139715, "test_0_acc1": 0.806, "test_0_acc5": 2.804, "test_5_loss": 6.844994894602477, "test_5_acc1": 0.55, "test_5_acc5": 1.958, "epoch": 0, "n_parameters": 22050664}
{"train_lr": 1.0000000000000031e-06, "train_loss": 6.846427675869634, "test_0_loss": 6.689390176393554, "test_0_acc1": 1.192, "test_0_acc5": 4.378, "test_5_loss": 6.844994894602477, "test_5_acc1": 0.55, "test_5_acc5": 1.958, "epoch": 1, "n_parameters": 22050664}
{"train_lr": 0.00020090000000000288, "train_loss": 6.701197089479981, "test_0_loss": 5.865309043488896, "test_0_acc1": 5.43, "test_0_acc5": 14.672, "test_5_loss": 6.844994894602477, "test_5_acc1": 0.55, "test_5_acc5": 1.958, "epoch": 2, "n_parameters": 22050664}
{"train_lr": 0.00040079999999998546, "train_loss": 6.543532955179588, "test_0_loss": 5.340847122768371, "test_0_acc1": 9.812, "test_0_acc5": 23.782, "test_5_loss": 6.844994894602477, "test_5_acc1": 0.55, "test_5_acc5": 1.958, "epoch": 3, "n_parameters": 22050664}
{"train_lr": 0.0006006999999999715, "train_loss": 6.4769038225916455, "test_0_loss": 5.03732673006796, "test_0_acc1": 13.248, "test_0_acc5": 29.602, "test_5_loss": 6.844994894602477, "test_5_acc1": 0.55, "test_5_acc5": 1.958, "epoch": 4, "n_parameters": 22050664}
{"train_lr": 0.0008006000000000287, "train_loss": 6.315360357340196, "test_0_loss": 5.300121459301969, "test_0_acc1": 10.944, "test_0_acc5": 25.546, "test_5_loss": 6.55244832365313, "test_5_acc1": 2.756, "test_5_acc5": 7.6525, "epoch": 5, "n_parameters": 22050664}
{"train_lr": 0.0010004999999999689, "train_loss": 6.190600837687318, "test_0_loss": 4.9149362563476755, "test_0_acc1": 14.35, "test_0_acc5": 31.418, "test_5_loss": 6.55244832365313, "test_5_acc1": 2.756, "test_5_acc5": 7.6525, "epoch": 6, "n_parameters": 22050664}
{"train_lr": 0.0012004000000000647, "train_loss": 6.088374964529566, "test_0_loss": 5.50498779843575, "test_0_acc1": 10.254, "test_0_acc5": 24.242, "test_5_loss": 6.55244832365313, "test_5_acc1": 2.756, "test_5_acc5": 7.6525, "epoch": 7, "n_parameters": 22050664}
{"train_lr": 0.0014002999999999238, "train_loss": 6.08913704293142, "test_0_loss": 4.774700349977363, "test_0_acc1": 14.72, "test_0_acc5": 32.384, "test_5_loss": 6.55244832365313, "test_5_acc1": 2.756, "test_5_acc5": 7.6525, "epoch": 8, "n_parameters": 22050664}
{"train_lr": 0.0016001999999999618, "train_loss": 6.150533516344121, "test_0_loss": 5.227625224198276, "test_0_acc1": 10.67, "test_0_acc5": 25.058, "test_5_loss": 6.55244832365313, "test_5_acc1": 2.756, "test_5_acc5": 7.6525, "epoch": 9, "n_parameters": 22050664}
{"train_lr": 0.0018001000000000126, "train_loss": 6.101692359891536, "test_0_loss": 5.141786843786161, "test_0_acc1": 11.414, "test_0_acc5": 26.346, "test_5_loss": 6.756372647642403, "test_5_acc1": 2.309, "test_5_acc5": 6.5675, "epoch": 10, "n_parameters": 22050664}
{"train_lr": 0.001951301233713633, "train_loss": 6.093319233182332, "test_0_loss": 4.774902591320924, "test_0_acc1": 14.368, "test_0_acc5": 31.786, "test_5_loss": 6.756372647642403, "test_5_acc1": 2.309, "test_5_acc5": 6.5675, "epoch": 11, "n_parameters": 22050664}
{"train_lr": 0.001941176365109525, "train_loss": 6.128870297345421, "test_0_loss": 5.251185640492503, "test_0_acc1": 11.492, "test_0_acc5": 26.726, "test_5_loss": 6.756372647642403, "test_5_acc1": 2.309, "test_5_acc5": 6.5675, "epoch": 12, "n_parameters": 22050664}
{"train_lr": 0.0019301276034588222, "train_loss": 6.053121808859752, "test_0_loss": 4.758080562108309, "test_0_acc1": 16.252, "test_0_acc5": 34.882, "test_5_loss": 6.756372647642403, "test_5_acc1": 2.309, "test_5_acc5": 6.5675, "epoch": 13, "n_parameters": 22050664}
{"train_lr": 0.0019181658525555538, "train_loss": 6.0439764577136055, "test_0_loss": 4.586510399862962, "test_0_acc1": 16.69, "test_0_acc5": 35.526, "test_5_loss": 6.756372647642403, "test_5_acc1": 2.309, "test_5_acc5": 6.5675, "epoch": 14, "n_parameters": 22050664}
{"train_lr": 0.0019053029172036828, "train_loss": 5.91496213320062, "test_0_loss": 4.488940908904268, "test_0_acc1": 17.398, "test_0_acc5": 36.698, "test_5_loss": 7.4814025707452325, "test_5_acc1": 1.2555, "test_5_acc5": 4.2435, "epoch": 15, "n_parameters": 22050664}
{"train_lr": 0.0018915514915675221, "train_loss": 6.002524321551898, "test_0_loss": 4.450921233922186, "test_0_acc1": 17.934, "test_0_acc5": 37.114, "test_5_loss": 7.4814025707452325, "test_5_acc1": 1.2555, "test_5_acc5": 4.2435, "epoch": 16, "n_parameters": 22050664}
{"train_lr": 0.0018769251466436458, "train_loss": 5.878266204508851, "test_0_loss": 4.308091710831062, "test_0_acc1": 20.404, "test_0_acc5": 41.2, "test_5_loss": 7.4814025707452325, "test_5_acc1": 1.2555, "test_5_acc5": 4.2435, "epoch": 17, "n_parameters": 22050664}
{"train_lr": 0.0018614383168689135, "train_loss": 5.789360093222343, "test_0_loss": 4.410817133793065, "test_0_acc1": 18.154, "test_0_acc5": 38.082, "test_5_loss": 7.4814025707452325, "test_5_acc1": 1.2555, "test_5_acc5": 4.2435, "epoch": 18, "n_parameters": 22050664}
{"train_lr": 0.0018451062858745686, "train_loss": 5.750880390286541, "test_0_loss": 4.467262921391278, "test_0_acc1": 19.266, "test_0_acc5": 39.462, "test_5_loss": 7.4814025707452325, "test_5_acc1": 1.2555, "test_5_acc5": 4.2435, "epoch": 19, "n_parameters": 22050664}
{"train_lr": 0.0018279451714032378, "train_loss": 5.764791792602562, "test_0_loss": 4.67896575738586, "test_0_acc1": 17.392, "test_0_acc5": 37.15, "test_5_loss": 7.557907587735987, "test_5_acc1": 0.9905, "test_5_acc5": 3.1575, "epoch": 20, "n_parameters": 22050664}
{"train_lr": 0.0018099719094030393, "train_loss": 5.759131700348416, "test_0_loss": 4.419680974762636, "test_0_acc1": 19.966, "test_0_acc5": 40.798, "test_5_loss": 7.557907587735987, "test_5_acc1": 0.9905, "test_5_acc5": 3.1575, "epoch": 21, "n_parameters": 22050664}
{"train_lr": 0.0017912042373137494, "train_loss": 5.710006896111605, "test_0_loss": 4.2751427415236405, "test_0_acc1": 20.356, "test_0_acc5": 41.114, "test_5_loss": 7.557907587735987, "test_5_acc1": 0.9905, "test_5_acc5": 3.1575, "epoch": 22, "n_parameters": 22050664}
{"train_lr": 0.0017716606765619972, "train_loss": 5.68051082098322, "test_0_loss": 4.154385426833091, "test_0_acc1": 21.638, "test_0_acc5": 43.102, "test_5_loss": 7.557907587735987, "test_5_acc1": 0.9905, "test_5_acc5": 3.1575, "epoch": 23, "n_parameters": 22050664}
{"train_lr": 0.0017513605142823508, "train_loss": 5.693617649811158, "test_0_loss": 4.25816687512535, "test_0_acc1": 20.994, "test_0_acc5": 41.96, "test_5_loss": 7.557907587735987, "test_5_acc1": 0.9905, "test_5_acc5": 3.1575, "epoch": 24, "n_parameters": 22050664}
{"train_lr": 0.0017303237842843694, "train_loss": 5.6821105527839695, "test_0_loss": 4.421267043301026, "test_0_acc1": 19.116, "test_0_acc5": 39.094, "test_5_loss": 8.897946262237587, "test_5_acc1": 0.514, "test_5_acc5": 1.892, "epoch": 25, "n_parameters": 22050664}
{"train_lr": 0.001708571247280513, "train_loss": 5.69677297047955, "test_0_loss": 4.398700253595852, "test_0_acc1": 19.178, "test_0_acc5": 39.536, "test_5_loss": 8.897946262237587, "test_5_acc1": 0.514, "test_5_acc5": 1.892, "epoch": 26, "n_parameters": 22050664}
{"train_lr": 0.0016861243703990647, "train_loss": 5.740358965097666, "test_0_loss": 4.446112109237348, "test_0_acc1": 19.972, "test_0_acc5": 40.84, "test_5_loss": 8.897946262237587, "test_5_acc1": 0.514, "test_5_acc5": 1.892, "epoch": 27, "n_parameters": 22050664}
{"train_lr": 0.0016630053059970855, "train_loss": 5.712303198760838, "test_0_loss": 4.1932648324234245, "test_0_acc1": 21.566, "test_0_acc5": 42.98, "test_5_loss": 8.897946262237587, "test_5_acc1": 0.514, "test_5_acc5": 1.892, "epoch": 28, "n_parameters": 22050664}
{"train_lr": 0.0016392368698000565, "train_loss": 5.74558376472631, "test_0_loss": 4.124165606513972, "test_0_acc1": 21.932, "test_0_acc5": 43.39, "test_5_loss": 8.897946262237587, "test_5_acc1": 0.514, "test_5_acc5": 1.892, "epoch": 29, "n_parameters": 22050664}
{"train_lr": 0.0016148425183847566, "train_loss": 5.3731044158518175, "test_0_loss": 4.680003530995935, "test_0_acc1": 15.374, "test_0_acc5": 33.588, "test_5_loss": 11.426024395688863, "test_5_acc1": 0.1075, "test_5_acc5": 0.45, "epoch": 30, "n_parameters": 22050664}
{"train_lr": 0.0015898463260310706, "train_loss": 4.259690835869474, "test_0_loss": 5.981102620495181, "test_0_acc1": 5.786, "test_0_acc5": 14.55, "test_5_loss": 11.426024395688863, "test_5_acc1": 0.1075, "test_5_acc5": 0.45, "epoch": 31, "n_parameters": 22050664}
{"train_lr": 0.0015642729609628443, "train_loss": 4.075305948785836, "test_0_loss": 5.933592574686403, "test_0_acc1": 4.598, "test_0_acc5": 13.066, "test_5_loss": 11.426024395688863, "test_5_acc1": 0.1075, "test_5_acc5": 0.45, "epoch": 32, "n_parameters": 22050664}
{"train_lr": 0.001538147661004018, "train_loss": 4.167220209940351, "test_0_loss": 6.295307500501207, "test_0_acc1": 3.228, "test_0_acc5": 9.566, "test_5_loss": 11.426024395688863, "test_5_acc1": 0.1075, "test_5_acc5": 0.45, "epoch": 33, "n_parameters": 22050664}
{"train_lr": 0.001511496208671658, "train_loss": 4.134730825523774, "test_0_loss": 5.972504679850104, "test_0_acc1": 3.806, "test_0_acc5": 11.758, "test_5_loss": 11.426024395688863, "test_5_acc1": 0.1075, "test_5_acc5": 0.45, "epoch": 34, "n_parameters": 22050664}
{"train_lr": 0.0014843449057311518, "train_loss": 4.365966309007885, "test_0_loss": 6.5958606600380065, "test_0_acc1": 2.156, "test_0_acc5": 7.3, "test_5_loss": 12.839466273136347, "test_5_acc1": 0.002, "test_5_acc5": 0.0035, "epoch": 35, "n_parameters": 22050664}
{"train_lr": 0.00145672054724078, "train_loss": 4.49492947772729, "test_0_loss": 6.905164708865429, "test_0_acc1": 1.588, "test_0_acc5": 5.264, "test_5_loss": 12.839466273136347, "test_5_acc1": 0.002, "test_5_acc5": 0.0035, "epoch": 36, "n_parameters": 22050664}
{"train_lr": 0.0014286503951072877, "train_loss": 4.562651729769558, "test_0_loss": 6.958603466617245, "test_0_acc1": 1.594, "test_0_acc5": 5.226, "test_5_loss": 12.839466273136347, "test_5_acc1": 0.002, "test_5_acc5": 0.0035, "epoch": 37, "n_parameters": 22050664}
{"train_lr": 0.0014001621511816529, "train_loss": 4.620032903101804, "test_0_loss": 6.883705623624269, "test_0_acc1": 1.946, "test_0_acc5": 5.582, "test_5_loss": 12.839466273136347, "test_5_acc1": 0.002, "test_5_acc5": 0.0035, "epoch": 38, "n_parameters": 22050664}
{"train_lr": 0.0013712839299212382, "train_loss": 4.635755813831715, "test_0_loss": 7.244386745887312, "test_0_acc1": 0.964, "test_0_acc5": 3.976, "test_5_loss": 12.839466273136347, "test_5_acc1": 0.002, "test_5_acc5": 0.0035, "epoch": 39, "n_parameters": 22050664}
{"train_lr": 0.0013420442306441068, "train_loss": 4.83734727265547, "test_0_loss": 7.3013705145603405, "test_0_acc1": 1.686, "test_0_acc5": 4.768, "test_5_loss": 14.802937962195847, "test_5_acc1": 0.0, "test_5_acc5": 0.0, "epoch": 40, "n_parameters": 22050664}
{"train_lr": 0.0013124719094030884, "train_loss": 4.639803186094732, "test_0_loss": 6.876579631236754, "test_0_acc1": 2.018, "test_0_acc5": 5.798, "test_5_loss": 14.802937962195847, "test_5_acc1": 0.0, "test_5_acc5": 0.0, "epoch": 41, "n_parameters": 22050664}
{"train_lr": 0.0012825961505090746, "train_loss": 4.412084535252657, "test_0_loss": 6.591678983037927, "test_0_acc1": 2.59, "test_0_acc5": 7.618, "test_5_loss": 14.802937962195847, "test_5_acc1": 0.0, "test_5_acc5": 0.0, "epoch": 42, "n_parameters": 22050664}
{"train_lr": 0.0012524464377290374, "train_loss": 4.6709612140790835, "test_0_loss": 6.897290852766958, "test_0_acc1": 1.53, "test_0_acc5": 4.804, "test_5_loss": 14.802937962195847, "test_5_acc1": 0.0, "test_5_acc5": 0.0, "epoch": 43, "n_parameters": 22050664}
{"train_lr": 0.0012220525251895084, "train_loss": 4.6320851319175445, "test_0_loss": 6.800072133197895, "test_0_acc1": 1.796, "test_0_acc5": 5.904, "test_5_loss": 14.802937962195847, "test_5_acc1": 0.0, "test_5_acc5": 0.0, "epoch": 44, "n_parameters": 22050664}
{"train_lr": 0.0011914444080128512, "train_loss": 4.503620743918286, "test_0_loss": 6.575515723884372, "test_0_acc1": 2.022, "test_0_acc5": 6.558, "test_5_loss": 14.347287286037218, "test_5_acc1": 0.0, "test_5_acc5": 0.0015, "epoch": 45, "n_parameters": 22050664}
{"train_lr": 0.0011606522927150055, "train_loss": 4.428880820481135, "test_0_loss": 6.934644104804431, "test_0_acc1": 1.686, "test_0_acc5": 5.35, "test_5_loss": 14.347287286037218, "test_5_acc1": 0.0, "test_5_acc5": 0.0015, "epoch": 46, "n_parameters": 22050664}
{"train_lr": 0.0011297065673964526, "train_loss": 4.419652088035306, "test_0_loss": 6.802638011793257, "test_0_acc1": 1.812, "test_0_acc5": 5.718, "test_5_loss": 14.347287286037218, "test_5_acc1": 0.0, "test_5_acc5": 0.0015, "epoch": 47, "n_parameters": 22050664}
{"train_lr": 0.001098637771751961, "train_loss": 4.502787098467207, "test_0_loss": 6.771555305671326, "test_0_acc1": 1.914, "test_0_acc5": 6.026, "test_5_loss": 14.347287286037218, "test_5_acc1": 0.0, "test_5_acc5": 0.0015, "epoch": 48, "n_parameters": 22050664}
{"train_lr": 0.0010674765669316342, "train_loss": 4.494316954335434, "test_0_loss": 6.48595598212283, "test_0_acc1": 2.612, "test_0_acc5": 7.744, "test_5_loss": 14.347287286037218, "test_5_acc1": 0.0, "test_5_acc5": 0.0015, "epoch": 49, "n_parameters": 22050664}
{"train_lr": 0.0010362537052827335, "train_loss": 4.489614735690238, "test_0_loss": 6.446241735115466, "test_0_acc1": 3.2, "test_0_acc5": 9.112, "test_5_loss": 13.726823627376739, "test_5_acc1": 0.0, "test_5_acc5": 0.0, "epoch": 50, "n_parameters": 22050664}
{"train_lr": 0.0010050000000000037, "train_loss": 4.393263733310761, "test_0_loss": 6.486784024339262, "test_0_acc1": 2.742, "test_0_acc5": 8.12, "test_5_loss": 13.726823627376739, "test_5_acc1": 0.0, "test_5_acc5": 0.0, "epoch": 51, "n_parameters": 22050664}
{"train_lr": 0.0009737462947172503, "train_loss": 4.560509789452183, "test_0_loss": 6.658233853082053, "test_0_acc1": 2.67, "test_0_acc5": 7.708, "test_5_loss": 13.726823627376739, "test_5_acc1": 0.0, "test_5_acc5": 0.0, "epoch": 52, "n_parameters": 22050664}
{"train_lr": 0.0009425234330683621, "train_loss": 5.009399911315797, "test_0_loss": 6.2143151386380575, "test_0_acc1": 3.152, "test_0_acc5": 9.528, "test_5_loss": 13.726823627376739, "test_5_acc1": 0.0, "test_5_acc5": 0.0, "epoch": 53, "n_parameters": 22050664}
{"train_lr": 0.000911362228248123, "train_loss": 5.013029120141844, "test_0_loss": 6.08363627594248, "test_0_acc1": 3.782, "test_0_acc5": 10.824, "test_5_loss": 13.726823627376739, "test_5_acc1": 0.0, "test_5_acc5": 0.0, "epoch": 54, "n_parameters": 22050664}
{"train_lr": 0.0008802934326035375, "train_loss": 4.750451637853345, "test_0_loss": 6.3756702597600405, "test_0_acc1": 2.726, "test_0_acc5": 8.558, "test_5_loss": 14.143242873218071, "test_5_acc1": 0.0, "test_5_acc5": 0.0, "epoch": 55, "n_parameters": 22050664}
{"train_lr": 0.0008493477072850013, "train_loss": 4.465096837015365, "test_0_loss": 6.296702206783087, "test_0_acc1": 3.32, "test_0_acc5": 9.52, "test_5_loss": 14.143242873218071, "test_5_acc1": 0.0, "test_5_acc5": 0.0, "epoch": 56, "n_parameters": 22050664}
{"train_lr": 0.0008185555919872402, "train_loss": 4.250373609250874, "test_0_loss": 6.6528933470781535, "test_0_acc1": 2.132, "test_0_acc5": 6.814, "test_5_loss": 14.143242873218071, "test_5_acc1": 0.0, "test_5_acc5": 0.0, "epoch": 57, "n_parameters": 22050664}
{"train_lr": 0.0007879474748104683, "train_loss": 4.126220693655437, "test_0_loss": 6.533459776441638, "test_0_acc1": 2.544, "test_0_acc5": 7.838, "test_5_loss": 14.143242873218071, "test_5_acc1": 0.0, "test_5_acc5": 0.0, "epoch": 58, "n_parameters": 22050664}
{"train_lr": 0.0007575535622709853, "train_loss": 4.028016795583671, "test_0_loss": 6.187997623353301, "test_0_acc1": 3.31, "test_0_acc5": 9.488, "test_5_loss": 14.143242873218071, "test_5_acc1": 0.0, "test_5_acc5": 0.0, "epoch": 59, "n_parameters": 22050664}
{"train_lr": 0.0007274038494909391, "train_loss": 4.133183625199907, "test_0_loss": 6.894926928436611, "test_0_acc1": 2.182, "test_0_acc5": 6.68, "test_5_loss": 13.754674187853636, "test_5_acc1": 0.0, "test_5_acc5": 0.006, "epoch": 60, "n_parameters": 22050664}
{"train_lr": 0.0006975280905969615, "train_loss": 4.215247207777582, "test_0_loss": 7.201413431307938, "test_0_acc1": 1.62, "test_0_acc5": 5.378, "test_5_loss": 13.754674187853636, "test_5_acc1": 0.0, "test_5_acc5": 0.006, "epoch": 61, "n_parameters": 22050664}
{"train_lr": 0.0006679557693559086, "train_loss": 3.9590489638151882, "test_0_loss": 6.334835453706145, "test_0_acc1": 2.748, "test_0_acc5": 8.556, "test_5_loss": 13.754674187853636, "test_5_acc1": 0.0, "test_5_acc5": 0.006, "epoch": 62, "n_parameters": 22050664}
{"train_lr": 0.0006387160700787183, "train_loss": 4.234101979030694, "test_0_loss": 6.17777241214452, "test_0_acc1": 4.1, "test_0_acc5": 11.14, "test_5_loss": 13.754674187853636, "test_5_acc1": 0.0, "test_5_acc5": 0.006, "epoch": 63, "n_parameters": 22050664}
{"train_lr": 0.0006098378488184052, "train_loss": 6.175165850005085, "test_0_loss": 5.8955679909967875, "test_0_acc1": 6.682, "test_0_acc5": 17.684, "test_5_loss": 13.754674187853636, "test_5_acc1": 0.0, "test_5_acc5": 0.006, "epoch": 64, "n_parameters": 22050664}
{"train_lr": 0.0005813496048927557, "train_loss": 5.201749606026734, "test_0_loss": 6.1827636899966425, "test_0_acc1": 3.974, "test_0_acc5": 10.682, "test_5_loss": 17.204989120278388, "test_5_acc1": 0.0, "test_5_acc5": 0.004, "epoch": 65, "n_parameters": 22050664}
{"train_lr": 0.000553279452759166, "train_loss": 6.5854629258171835, "test_0_loss": 6.433814403878063, "test_0_acc1": 3.956, "test_0_acc5": 10.828, "test_5_loss": 17.204989120278388, "test_5_acc1": 0.0, "test_5_acc5": 0.004, "epoch": 66, "n_parameters": 22050664}
{"train_lr": 0.0005256550942687854, "train_loss": 5.556410076401884, "test_0_loss": 5.778084488915695, "test_0_acc1": 5.26, "test_0_acc5": 14.46, "test_5_loss": 17.204989120278388, "test_5_acc1": 0.0, "test_5_acc5": 0.004, "epoch": 67, "n_parameters": 22050664}
{"train_lr": 0.0004985037913283868, "train_loss": 4.341524729339911, "test_0_loss": 7.4646278977851726, "test_0_acc1": 2.578, "test_0_acc5": 6.944, "test_5_loss": 17.204989120278388, "test_5_acc1": 0.0, "test_5_acc5": 0.004, "epoch": 68, "n_parameters": 22050664}
{"train_lr": 0.0004718523389959182, "train_loss": 3.956535089227984, "test_0_loss": 7.080361831211083, "test_0_acc1": 2.634, "test_0_acc5": 7.304, "test_5_loss": 17.204989120278388, "test_5_acc1": 0.0, "test_5_acc5": 0.004, "epoch": 69, "n_parameters": 22050664}

**Comment by ksouvik52** [comment]
I used the exact same script, with --nproc_per_node=4.

**Comment by ytongbai** [comment]
Hi, please see this for a fix, thanks so much!
https://github.com/ytongbai/ViTs-vs-CNNs/issues/8#issuecomment-1193216087
